title: Teatro 700
email: vedph@unive.it
baseurl: /teatro700

markdown: kramdown
permalink: pretty

collections:
  personaggi:
    output: true
  opere:
    output: true

languages:
  it: Italiano
  de: Tedesco
  ru: Russo
